FROM apache/airflow:2.7.1-python3.11

WORKDIR /opt/airflow

USER airflow

RUN pip install --upgrade pip
RUN pip install pandas==2.3.3 boto3==1.28.17 dbfread==2.0.7
RUN pip install dbt-postgres==1.6.1 psycopg2-binary==2.9.7
RUN pip install datasus-dbc==0.1.3 pyarrow==11.0.0
RUN pip install python-dotenv